### ISSUE TITLE
Java Coding Style and Naming Conventions

### ISSUE THREAD

**Issue by rumaan** [akashdeepb/SOSCVerifier#3]
Check this out @akashdeepb ➡️ [Android Dev Guidelines](https://github.com/mike14u/android-development-guidelines)

**Comment by rumaan** [comment]
https://github.com/akashdeepb/SOSCVerifier/blob/513817b057193ec8c840a0436952b881713f0c97/app/src/main/java/com/example/adb7473/soscverifier/MainActivity.java#L30-L33

**Comment by rumaan** [comment]
Add this ➡️ [Square Code Style](https://github.com/square/java-code-styles)

**Comment by haxzie-xx** [comment]
Boi @akashdeepb this ain't php to start naming from _ underscores.. use CamelCases :laughing:
