### ISSUE TITLE
Move hardcoded strings to strings.xml

### ISSUE THREAD

**Issue by haxzie-xx** [akashdeepb/SOSCVerifier#7]
We had done this mistake. It's a good practice to move all the string values that are being used in the layout files to be separated into `strings.xml` file.
https://github.com/akashdeepb/SOSCVerifier/blob/9cf5974d607fbe2a25a6c06da0e2a47dc07844fb/app/src/main/res/layout/activity_main.xml#L38

**Comment by rumaan** [comment]
Even the ones which are being used in `Toast` 🍞 

https://github.com/akashdeepb/SOSCVerifier/blob/e583d4a35df0c2e3334b3211757ddcb5426cc6dc/app/src/main/java/com/example/adb7473/soscverifier/MainActivity.java#L74-L77
